name: "More books"
description: "Information about proposed textbook regulations in South Africa"

url: http://localhost:4000
baseurl: /morebooks
liveurl: http://morebooks.co.za

markdown: kramdown
permalink: pretty

exclude: [
send-mail.md,
example-letter.md,
have-your-say.md,
]